name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ******** test in pure python & uv venv first  *******
  integrate-and-test-pure-py-app:
    runs-on: ubuntu-latest
    env:
      MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
      MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
      MLFLOW_TRACKING_USERNAME: ${{secrets.MLFLOW_TRACKING_USERNAME}}
      MLFLOW_TRACKING_PASSWORD: ${{secrets.MLFLOW_TRACKING_PASSWORD}}
      DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_USER_TOKEN}}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: python installation
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: install dependecies
        run: uv sync --frozen --no-install-project

      - name: run python test
        run: uv run python -m pytest

  # ******** test in docker container second *******

  integrate-and-test-docker-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: run docker compose
        env:
          MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
          MLFLOW_TRACKING_USERNAME: ${{secrets.MLFLOW_TRACKING_USERNAME}}
          MLFLOW_TRACKING_PASSWORD: ${{secrets.MLFLOW_TRACKING_PASSWORD}}
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_USER_TOKEN}}
        run: docker compose up -d --build --wait

      - name: test the app
        run: |
          docker compose exec myapp uv run python -m pytest

  build-and-deploy-on-aws:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    needs: integrate-and-test-docker-app
    steps:
      - name: load the code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::285515884731:role/credit-approval-ecr

      - name: login to aws ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Build and push to ECR
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: 285ش515884731.dkr.ecr.eu-north-1.amazonaws.com/credit-approval/credit-approval/app:latest